services:
  nginx:
    image: "laravel-docker:nginx"
    depends_on:
      - php
    volumes:
      - "./nginx/app.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
  php:
    image: "laravel-docker:php"
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      APP_NAME: "Laravel Docker"
      APP_ENV: "production"
      APP_KEY: "base64:Avm4zs1yLfogxHpwBZRZhKZJ0EC6/7IX0FcVSyQQlLU="
      APP_DEBUG: "false"
      APP_URL: "http://localhost"
      LOG_CHANNEL: "stderr"
      # Postgres configuration
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_DATABASE: "laravel-app"
      DB_USERNAME: "laravel"
      DB_PASSWORD: "password"
      # Redis configuration
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      BROADCAST_DRIVER: "redis"
      CACHE_DRIVER: "redis"
      QUEUE_CONNECTION: "redis"
      SESSION_DRIVER: "redis"
      # Minio configuration
      FILESYSTEM_DISK: "s3"
      AWS_ACCESS_KEY_ID: "laravel"
      AWS_SECRET_ACCESS_KEY: "password"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_BUCKET: "local"
      AWS_URL: "http://localhost:9000"
      AWS_ENDPOINT: "http://minio:9000"
      AWS_USE_PATH_STYLE_ENDPOINT: "true"
  postgres:
    image: "postgres:15"
    environment:
      PGPASSWORD: "password"
      POSTGRES_DB: "laravel-app"
      POSTGRES_USER: "laravel"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "laravel-app", "-U", "laravel" ]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  minio:
    image: "minio/minio:latest"
    environment:
      MINIO_ROOT_USER: "laravel"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - "minio-data:/data/minio"
    command: "minio server /data/minio --console-address ':8900'"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      retries: 3
      timeout: 5s
volumes:
  postgres-data: { }
  redis-data: { }
  minio-data: { }